compressionLevel: 0
nodeLinker: node-modules
npmPublishAccess: public
npmPublishRegistry: https://registry.npmjs.org/
# This line can be ommited if corepack is enabled (requires the packageManager field in package.json)
yarnPath: .yarn/releases/yarn-3.6.1.cjs
